### ISSUE TITLE
Image control is broken in latest development build

### ISSUE THREAD

**Issue by mshakour** [themeum/kirki#1368]
### Issue description:
Image Control `'type' => 'image',` is not working properly, when i click (select file) nothing is happening, although it was working seamlessly in a dev build i have downloaded back in June 2nd.

### Version used:
Latest Development Build

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Can you please try this again?
I just pushed another commit for image controls that should fix most issues.

**Comment by aristath** [comment]
If you're still having an issue, can you please tell me how many controls you've got in total? If you give it a minute and then try pressing the button, does it work then? I pushed a performance-boosting tweak a couple of days ago so wondering if this is to blame

**Comment by mshakour** [comment]
I'm afraid the whole controls have disappeared completely after using the latest dev build!

I tried also to remove all controls and use only one control but the problem is still present, all controls including default ones are disappeared.

See attached image.
![kirki](https://user-images.githubusercontent.com/6414967/27006747-a9011d88-4e3c-11e7-8ca2-0e1647f09393.jpg)

**Comment by aristath** [comment]
There was a typo, should be fixed now.
