### ISSUE TITLE
Kirki Assets 404 when using a child theme

### ISSUE THREAD

**Issue by leanda** [themeum/kirki#1500]
### Issue description:
I have kirki embedded in a theme when using a child theme I get 404 errors for the assets and css, I'm guessing that's because it's looking for the inc directory in the child theme and it doesn't exist. When using in a child theme is the only option to copy the kirki folder into the theme or can it be included without duplicating the whole folder to the child theme.

Also commented here earlier as it's a similar issue #723 

### Version used: 2.3.7
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by aristath** [comment]
@leanda sorry it took me so long to get back to you

Have you tried updating to the latest stable version?
A lot of things have been fixed since version 2.3.7!

**Comment by leanda** [comment]
I haven't actually. I'll give that a go in the next few days and see if that fixes the issue.

**Comment by leanda** [comment]
Hi @aristath 

I've just updated to v3.0.9 and I'm afraid it doesn't solve the issue. I have two customers using my theme as a child theme who have reported the same issue this week and I'm able to replicate the same issue which only happens with child themes. For now I've told them to copy the /inc/ folder to the child theme as it's the only way I can see to get around the issue.

Any other ideas? I'm stumped!

**Comment by aristath** [comment]
Is your child theme somewhere on github perhaps so that I may test it?

**Comment by leanda** [comment]
It's not is there another way I can send it to you without making it public?

Thanks

**Comment by aristath** [comment]
You could put it on dropbox for example and send me an email with the link. If the parent theme is not a free theme then please add that too.
