### ISSUE TITLE
ToolTip not showing

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1502]
Hey there,

I used the GitHub version of Kirki, (https://github.com/aristath/kirki), to correct the issue I had with Kirki not outputting percent based values: https://wordpress.org/support/topic/dimension-control-not-outputting-percentage-based-value/, worked as you stated it would, however I noticed another issue after I did that.

The tooltips do not seem to be showing as they should. They show for the typography controls I added but for the others they are a no show.

When I use the plugin from WordPress.org they show up fine, but when I use the GitHub version they disappear.

**Comment by aristath** [comment]
Hey there!

Version 3.0.10 includes a lot of performance improvements and a lot of the code changed in order to achieve that (HUGE performance boost if you're using many controls).
Tooltips were just fixed in the develop branch 👍

**Comment by tsquez** [comment]
Awesome news amigo. Can't wait to show you what I have in store :smiley:

**Comment by tsquez** [comment]
Actually I just downloaded the dev version again (cloned it...even cloned the kirki-controls) and the tooltips are still not showing.

**Comment by tsquez** [comment]
Now I'm getting a lot of this showing up:

**_Please wait while we load the control_** :question::question::question:

**Comment by aristath** [comment]
Have you tried resetting your browser caches? 
I had that issue too last week, a simple hard refresh fixed it for me

**Comment by tsquez** [comment]
OK some of the tooltips came back after hard refresh and still getting **_Please wait while we load the control_** on some controls

**Comment by aristath** [comment]
Can you please provide some more details?
Which controls?
Is it a specific control type?
Is it controls that have something in common?
If so, what is it that they have in common?

**Comment by tsquez** [comment]
DOH... yeah it would be best to provide more info...lol sorry about that. They are text controls and they are both built the same way with the exception they have different names and they are both in the same section.
