### ISSUE TITLE
E_WARNING: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#153]
Im currently running the develop branch on my system and New Relic is freaking out with the following notices:

```
Error message
E_WARNING: Invalid argument supplied for foreach()

Sample stack trace
…s/wordpress/wp-content/themes/wip-roots/lib/kirki/includes/Styles/
Frontend.php (178)
…s/wordpress/wp-content/themes/wip-roots/lib/kirki/includes/Styles/
Frontend.php (47)
…s/wordpress/wp-content/themes/wip-roots/lib/kirki/includes/Styles/
Frontend.php (17)
in Kirki\Styles\Frontend::enqueue_styles called at ? (?)
…call_user_func_array called at /srv/wordpress/wordpress/wp-includes/
plugin.php (496)
in do_action called at /srv/wordpress/wordpress/wp-includes/script-loader.php (923)
in wp_enqueue_scripts called at ? (?)
…call_user_func_array called at /srv/wordpress/wordpress/wp-includes/
plugin.php (496)
… do_action called at /srv/wordpress/wordpress/wp-includes/
general-template.php (2197)
in wp_head called at ? (?)
…/srv/wordpress/wordpress/wp-content/plugins/timber-library/lib/
timber-twig.php (191)
in TimberTwig::exec_function called at ? (?)
…ess/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Environment.php(332) : eval()'d code (60)
…press/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Template.php (289)
…press/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Template.php (263)
…ess/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Environment.php(332) : eval()'d code (211)
…press/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Template.php (154)
…ess/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Environment.php(332) : eval()'d code (27)
…press/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Template.php (289)
…press/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/
Template.php (263)

```

**Comment by aristath** [comment]
Fixed. :)

**Comment by lmartins** [comment]
Hi again,
Im afraid theres a situation where it still happens:

```
[03-Apr-2015 10:48:22 UTC] PHP Warning:  Invalid argument supplied for foreach() in /srv/wordpress/wordpress/wp-content/themes/wip-roots/lib/kirki/includes/Scripts/Frontend/GoogleFonts.php on line 21
```

**Comment by aristath** [comment]
Hey there!

Do google fonts work on your installation?
That file creates the script that's needed to fetch the google-fonts.
However, from that error it looks like it can't even detect that any fields exist which is... weird!

**Comment by lmartins** [comment]
Weird, I'm not at the computer right now but I know I'm not using Google fonts at the moment.
