### ISSUE TITLE
Bug in toggle field when used in expanded section

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1559]
### Issue description:
I have a bug with the toggle field when used in a expanded section.
Please see attached images.

### Version used:
Version 3.0.10

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

```
add_action( 'after_setup_theme', 'homepage_sections' );

function homepage_sections()
{

	Kirki::add_section( 'home-sections', array(
		'title'			=> esc_attr__( 'Home Page Sections', 'andy' ),
		'priority'		=> 1,
		'capability'	=> 'edit_theme_options',
		'type' 			=> 'expanded',
	));

}






add_action( 'after_setup_theme', 'homepage_sections_fields' );

function homepage_sections_fields()
{

	Kirki::add_field( 'andy', array(
		'type'        => 'toggle',
		'settings'    => 'home-section-1-on',
		'label'       => __( 'Enable the Works Section 1', 'andy' ),
		'section'     => 'home-sections',
		'default'     => '1',
		'priority'    => 10,
	));

	Kirki::add_field( 'andy', array(
		'type'        => 'toggle',
		'settings'    => 'home-section-2-on',
		'label'       => __( 'Section 2', 'andy' ),
		'section'     => 'home-sections',
		'default'     => '1',
		'priority'    => 10,
	));

}
```

The toggles don't show, this code gives me this output:
![captura de ecra 2017-10-03 as 17 17 23](https://user-images.githubusercontent.com/6692380/31136032-d7c8d094-a85e-11e7-8fd3-794bf2e27d6e.png)

If i erase or comment the` 'type' => 'expanded' `line everything works:
![captura de ecra 2017-10-03 as 17 12 22](https://user-images.githubusercontent.com/6692380/31135942-8ede86b2-a85e-11e7-99b9-f9f376d6c23d.png)

---

I'm using your _s theme with a clean WP install for these tests.

Thanks!

**Comment by Xstyler85** [comment]
I have the same problem

**Comment by aristath** [comment]
Fixed

**Comment by Xstyler85** [comment]
This problem still persists for me, but I don't use _s theme.

**Comment by aristath** [comment]
@Xstyler85 can you please try using the latest develop branch? I can no longer replicate this one

**Comment by DannyCooper** [comment]
Tested and working in `master` and `develop`.
