### ISSUE TITLE
Spacing Control with "Auto" setting for left and right margins

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1671]
Adding this here from https://wordpress.org/support/topic/spacing-question-2/#post-9723196 per your request.

Just so you remember it should give the user the option to set the margins for the left and right to `auto`

This will be awesome 🥇

**Comment by aristath** [comment]
done, can you please test it in the develop branch? Thanks!

**Comment by tsquez** [comment]
Just tried this with WP 4.9 and the dev version of Kirki and I still get the following:

`Invalid Value (Left,Right)`

**Comment by aristath** [comment]
Seems to be working fine now on my end... One more test? Remember to reset your browser caches just in case it loads previous versions of the JS files.
https://github.com/aristath/kirki/archive/develop.zip

**Comment by tsquez** [comment]
Yes you are correct, does seem to be working now.

**Comment by aristath** [comment]
Awesome, thanks for checking!
