### ISSUE TITLE
Kirki Styles location not being pulled in from passed 'url_path' in config

### ISSUE THREAD

**Issue by craigpearson** [themeum/kirki#235]
When you specify a url_path as a config parameter it no longer defines the constant KIRKI_URL. It always assumes the url is relative to the plugin directory as opposed to theme directory.

This commit broke this: https://github.com/reduxframework/kirki/blame/dbcbc2dcffe61f65b931da7df57896c71669d3c1/kirki.php#L18

i.e. instead of http://example.com/wp-content/themes/THEMENAME/lib/kirki/assets/css/kirki-styles.css

The style is called from

http://v3.fatsomasitesdev.com/wp-content/plugins/ABSOLUTEPATH/wp-content/themes/THEMENAME/lib/kirki/assets/css/kirki-styles.css

This results in an error output by the page

**Comment by aristath** [comment]
Hey there! Can you please check now?
I believe this was just fixed

**Comment by CraigPearson** [comment]
Yep that seems to have fixed it!

Thanks a tonne

**Comment by craigpearson** [comment]
Apologies this isn't actually fixed, it's still spitting out the absolute path to the css file and then appending that to http://example.com/wp-content/plugins/ABSOLUTEPATH

Which leads me to believe that somewhere the url http://example.com/wp-content/plugins/ is hard coded as this is implemented as a theme inclusion not a plugin
