### ISSUE TITLE
Select2 Multiple: inconsistent behavior in saving options

### ISSUE THREAD

**Issue by pagelab** [themeum/kirki#284]
It does not trigger imediately the "Save and Publish" button if there's no option specified in the filed. 

For now, in order to trigger the save function, it's necessary to select and delete any other option:

![select2-multiple-saving](https://cloud.githubusercontent.com/assets/1451087/8889815/d1b5340c-32bf-11e5-8af5-c82543578834.gif)

**Comment by pdufour** [comment]
I think #320 should fix this.

**Comment by aristath** [comment]
@pagelab I just merged the @pdufour's PR, can you check if that fixes your issue?

**Comment by pagelab** [comment]
Sorry for the delay! I tested this with the new select control, and the issue persists.

Also, with this new control, after deleting the option, the field shrinks a bit.

![select-kirki-bug](https://cloud.githubusercontent.com/assets/1451087/10003437/c062d024-6082-11e5-8168-c39c28569ea3.gif)

**Comment by aristath** [comment]
@pagelab Hey there!

I think that last commit just fixed this issue...
![select-multi-demo](https://cloud.githubusercontent.com/assets/588688/10010737/34050d7e-60f8-11e5-9e40-8c589575ddbc.gif)

Can you please confirm it works for you now?

**Comment by pagelab** [comment]
Yes, it works, thanks!

**Comment by Anydog** [comment]
Hi, guys . What's that screen gif capture app you're using ? A lot better then video screencasting for small presentation.

**Comment by fovoc** [comment]
@Anydog http://www.cockos.com/licecap/

**Comment by Anydog** [comment]
@fovoc Thank you very much !
