### ISSUE TITLE
Typography control does not working.

### ISSUE THREAD

**Issue by mrtieutien90** [themeum/kirki#525]
Latest Version of kirki not working with typography control.
Please check it.
Thanks.

**Comment by reshogun** [comment]
@mrtieutien90 do you have similar problem with me? I have made body font fields what seems right with wiki but when i try to change font type, it does not do anything. Surprisingly when i change sizes it seems to effect on customizer side but when i save changes, it does not carry these changes on main side.  @aristath  I am using recommended method to pass these changes on:  Here is the code i am using:

``` php
Kirki::add_field( '', array(
    'type'     => 'select',
    'settings' => 'base_typography_font_family',
    'label'    => __( 'Font Family', 'example' ),
    'section'  => 'base_typography',
    'default'  => 'Roboto',
    'priority' => 20,
    'choices'  => Kirki_Fonts::get_font_choices(),
    'output'   => array(
        'element'  => 'body',
        'property' => 'font-family',
    ),
) );

Kirki::add_field( '', array(
    'type'        => 'multicheck',
    'settings'    => 'base_typography_subsets',
    'label'       => __( 'Google-Font subsets', 'example' ),
    'description' => __( 'The subsets used from Google\'s API.', 'example' ),
    'section'     => 'base_typography',
    'default'     => 'all',
    'priority'    => 22,
    'choices'     => Kirki_Fonts::get_google_font_subsets(),
    'output'      => array(
        'element'  => 'body',
        'property' => 'font-subset',
    ),
) );

Kirki::add_field( '', array(
    'type'     => 'slider',
    'settings' => 'base_typography_font_weight',
    'label'    => __( 'Font Weight', 'example' ),
    'section'  => 'base_typography',
    'default'  => 300,
    'priority' => 24,
    'choices'  => array(
        'min'  => 100,
        'max'  => 900,
        'step' => 100,
    ),
    'output'   => array(
        'element'  => 'body',
        'property' => 'font-weight',
    ),
) );

Kirki::add_field( '', array(
    'type'      => 'slider',
    'settings'  => 'base_typography_font_size',
    'label'     => __( 'Font Size', 'example' ),
    'section'   => 'base_typography',
    'default'   => 14,
    'priority'  => 25,
    'choices'   => array(
        'min'   => 7,
        'max'   => 48,
        'step'  => 1,
    ),
    'output' => array(
        'element'  => 'body',
        'property' => 'font-size',
        'units'    => 'px',
    ),
    'transport' => 'postMessage',
    'js_vars'   => array(
        array(
            'element'  => 'body',
            'function' => 'css',
            'property' => 'font-size',
            'units'    => 'px'
        ),
    ),
) );  
```

**Comment by JayneshV** [comment]
Yes,

I've tried everything and output just doesn't work. Everyone claims that it works but it actually doesn't. It only works in the customizer. When you save it and go to the main site it css isn't being outputted.

**Comment by JayneshV** [comment]
It's all coming down to Kirki::$fields not outputting the fields but for some reason it outputs it in customizer.

**Comment by cubell** [comment]
I also used the demo code provided in the docs, and it doesn't work for me either. It seems to be because in class-kirki-styles-output-css.php the $output['sanitize_callback'] value on line 166 is returning the wrong function name for the call_user_fun to run.

**Comment by aristath** [comment]
@mrtieutien90 @reshogun @JayneshV @cubell are you only having this issue for the typography control? Or is it something that happens for ALL control-types?

**Comment by cubell** [comment]
@aristath It only seems to happen on options with an 'output' argument.

**Comment by visurel** [comment]
@aristath Followed the documentation step-by-step and getting the same result.
It definitely has something to do with the "generation" of the CSS in the 'output' field, as `/wp-admin/admin-ajax.php?action=kirki_dynamic_css` returns nothing.

@reshogun Font size is changing in the Customizer because it's not reloading, but instead modifying the body-element directly with JavaScript, so that's why it's not saving the result.

**Comment by aristath** [comment]
Can you try pulling the develop branch and use that instead of the master branch?
Let me know if that fixes the issue...
You can download the develop branch directly using this link: https://github.com/aristath/kirki/archive/develop.zip

**Comment by visurel** [comment]
@aristath It does not work. But `/wp-admin/admin-ajax.php?action=kirki_dynamic_css` is now returning `0` instead of nothing.

**Comment by aristath** [comment]
@EinArzt you mean that is's still enqueued? Are the styles not inline?

**Comment by aristath** [comment]
@EinArzt are you using theme_mods or options?
Can you please paste your config here so that I may try to replicate this issue? 'Cause so far it's working fine for me...

**Comment by ThomasFx** [comment]
@aristath @EinArzt 
Same problem, styles are both (dynamic - return 0) and inline - but they are loaded before theme stylesheet - so they cant override theme styles.
![inlinecss](https://cloud.githubusercontent.com/assets/16048842/11956064/a56d30e8-a8b7-11e5-9d32-7ff73adb42d3.jpg)

Trying disable inline css, but not work: 
$config['inline_css']   = false;

Using as plugin (from WP rep.,) and theme_mods - tested with master and dev version too

**Comment by aristath** [comment]
@ThomasFx Can you please try the develop branch again?
I believe this is fixed now...

**Comment by ThomasFx** [comment]
@aristath Excellent work. Working fine now. 
disabling inline css still not work (if is included in this branch)

The long loading issue is gone too - https://github.com/aristath/kirki/issues/535

**Comment by aristath** [comment]
Great!

I completely disabled the ajax method of adding styles for now so only the inline method works.
We obviously have to re-examine the AJAX implementation a bit before re-introducing it.
I'm closing this one. :+1:
