### ISSUE TITLE
Does 'transport' => 'auto' uses 'function' => 'css'?

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#784]
`'transport' => 'auto'` does not work with pseudo elements. I think it uses `css` as its `function`. If we change its `function` to `style` it would work for all CSS elements.

But I suppose you would have thought of this. Is there any downside of using `style` as `function` in `js_vars`?

**Comment by aristath** [comment]
I think this was just a typo... I used `strrpos` instead of `strpos` to check if the element contains the `:` character.
It should be working now, can you please confirm?
If you use something like `a:hover` it should pick up the `:` and understand that you're using pseudo-elements, switching automatically from `css` to `style`

**Comment by rahulnever2far** [comment]
It is not working perfectly.



```php
Kirki::add_config( 'config_test', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );

Kirki::add_panel( 'panel_test', array(
  'title' => esc_html__( 'Test Panel', 'test' ),
) );

Kirki::add_section( 'section_test', array(
  'title' => esc_html__( 'Test Section', 'test' ),
  'panel' => 'panel_test',
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_color',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Color', 'test' ),
  'type'      => 'color',
  'default'   => '#fff',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => "..test a",
      'property' => 'color',
    ),
  ),
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_background_color',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Background Color', 'test' ),
  'type'      => 'color',
  'default'   => '#222',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => "..test a",
      'property' => 'background-color',
    ),
  ),
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_color_hover',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Color', 'test' ),
  'type'      => 'color',
  'default'   => '#222',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => "..test a:hover",
      'property' => 'color',
    ),
  ),
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_background_color_hover',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Background Color', 'test' ),
  'type'      => 'color',
  'default'   => '#f00',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => "..test a:hover",
      'property' => 'background-color',
    ),
  ),
) );
```

**Comment by rahulv3a** [comment]
It is not working perfectly. Reason being, styles that `css` adds always override styles in `style`.

If you set colors in all four fields in the following code, hover colors stop working in Live Preview.

``` php
Kirki::add_config( 'config_test', array(
  'capability'  => 'edit_theme_options',
  'option_type' => 'theme_mod',
) );

Kirki::add_panel( 'panel_test', array(
  'title' => esc_html__( 'Test Panel', 'test' ),
) );

Kirki::add_section( 'section_test', array(
  'title' => esc_html__( 'Test Section', 'test' ),
  'panel' => 'panel_test',
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_color',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Color', 'test' ),
  'type'      => 'color',
  'default'   => '#fff',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => ".test a",
      'property' => 'color',
    ),
  ),
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_background_color',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Background Color', 'test' ),
  'type'      => 'color',
  'default'   => '#222',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => ".test a",
      'property' => 'background-color',
    ),
  ),
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_color_hover',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Color', 'test' ),
  'type'      => 'color',
  'default'   => '#222',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => ".test a:hover",
      'property' => 'color',
    ),
  ),
) );

Kirki::add_field( 'config_test', array(
  'settings'  => 'field_background_color_hover',
  'section'   => 'section_test',
  'label'     => esc_html__( 'Background Color', 'test' ),
  'type'      => 'color',
  'default'   => '#f00',
  'transport' => 'auto',
  'output'    => array(
    array(
      'element'  => ".test a:hover",
      'property' => 'background-color',
    ),
  ),
) );
```

I selected the following colors:
`field_color`: Yellow - rgb(238, 238, 34)
`field_background_color`: Red - rgb(221, 51, 51)
`field_color_hover`: Blue - #1e73be
`field_background_color_hover`: Green - #81d742

Chrome's code inspector shows the following:
![untitled-1](https://cloud.githubusercontent.com/assets/3503359/14073457/f1adee72-f4e6-11e5-8e5b-24df1723a0a6.jpg)

**Comment by rahulv3a** [comment]
Also, `'transport' => 'postMessage'` with `style` stopped working. I'm using [dc9bf08](https://github.com/aristath/kirki/commit/dc9bf083b464f02dab8462cd415547853a2468da).

**Comment by aristath** [comment]
Fixed. Can you please confirm? The code you posted above now works fine for me

**Comment by rahulv3a** [comment]
Hovers still have the same problem. If you change values just the hover field, it would work. However, if you change values to all four fields in the code I posted, it fails.

I assigned the values in the following order:
1. field_color
2. field_background_color
3. field_color_hover
4. field_background_color_hover

Chrome's code inspector shows the following:
![untitled-1](https://cloud.githubusercontent.com/assets/3503359/14103808/6da306f6-f5bf-11e5-960a-1b31b4820631.jpg)

As you can see `field_color_hover` & `field_background_color_hover` that are added in `<style>` in `<head>` are still being overridden by `field_color` and `field_background_color` that are added as incline css.

In my opinion the issue is, `field_color` and `field_background_color` are add with `'function' => 'css'`. `field_color_hover` and `field_background_color_hover` are added using `'function' => 'style'`.  Browser always prioritize inline css over `<style>` in `<head>` unless `!important` is supplied along with property value. If we add all of them using `'function' => 'style'`, it would solve the problem.

**Comment by aristath** [comment]
> Hovers still have the same problem. If you change values just the hover field, it would work. However, if you change values to all four fields in the code I posted, it fails.

You're right... in my tests I was only changing the hover color.

>  Browser always prioritize inline css over `<style>` in `<head>` unless !important is supplied along with property value. If we add all of them using `'function' => 'style'`, it would solve the problem.

Agreed.
Right now using `'function' => 'style'` just has some performance issues, that's why I haven't implemented it that way. I'm looking into ways of fixing that and I have a couple of thought, hopefully I'll have a patch ready soon.

**Comment by aristath** [comment]
ok, I believe this was finally solved. If you can test it and verify one more time I'd appreciate it... :+1: 
Problem was solved by creating a separate `<style>` in the `<head>`, each one of them with its own ID.
In the old implementation each time you were making a change, a new `<style>` was getting added. Now it just changes the contents of the `<style>` that has the ID of the setting.

**Comment by rahulv3a** [comment]
Each `<style>` with its own ID is a clever idea :100: 

Unfortunately, it is still not yet working correctly. But I think we are almost there :+1: 

Using the same test code I posted above, I performed some tests in order to help you figure out the problem.

Values of the following fields were:
`field_color`: #FFFFFF
1field_background_color`: #000000

I changed them to:
`field_color`:  #eeee22
`field_background_color`: #1e73be

Chrome's code inspector shows the following:
![untitled-1](https://cloud.githubusercontent.com/assets/3503359/14133040/63a6ed3e-f669-11e5-977b-1111c9b56f5c.jpg)

Values of the following fields were:
`field_color`:  #FFFFFF
1field_background_color`: #DD3333

I changed them to:
`field_color_hover`:  #00000
`field_background_color_hover`: #81d742

Chrome's code inspector shows the following:
![untitled-2](https://cloud.githubusercontent.com/assets/3503359/14133051/94f9e710-f669-11e5-9038-e0a1980ca7ab.jpg)

I think now the problem is the order of `<style>` in `<head>`. Default/Previously stored values are being added below the `<style>`s added by `'transport' => 'postMessage'`. That's why, changes made `'transport' => 'postMessage'` are always overridden by `<style>` that contains default/previously stored values. Rest you know better :)

**Comment by rahulv3a** [comment]
I'm trying to check if #781 is fixed. It seems like these changes affected `'transport' => 'postMessage'` as well.

I think `'function' => 'style'` is not working due to the same reason as 'transport' => 'auto', which is understandable.

The weird part is, now `'function' => 'css'` is also adding `<style>` tags in the `<head>`, instead of inline css.

**Comment by rahulv3a** [comment]
@aristath Could you please re-open the issue so that you don't forget to fix this? :)

**Comment by aristath** [comment]
> I'm trying to check if #781 is fixed. It seems like these changes affected 'transport' => 'postMessage' as well.

Seems to me like it's working fine! Did you find any issues while testing it?

> I think 'function' => 'style' is not working due to the same reason as 'transport' => 'auto', which is understandable.
> The weird part is, now 'function' => 'css' is also adding `<style>` tags in the `<head>`, instead of inline css.

Everything uses the `style` method now (except of course the `html` method).
`css` & `style` were kinda merged now that I finally fixed the performance issue I had.

**Comment by rahulv3a** [comment]
I just tested again. It is working fine :+1: 

Just tested #781. It ss fixed as well :+1: 

I went through my previous test file. I made the silliest mistake a developer could make, I spelled the name of the CSS class in `element` wrong.

I sincerely apologize for bothering you with this even after it was fixed.
