### ISSUE TITLE
Notice: Undefined index: default

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#86]
Hi,

Im getting a lot of Notices on my logs, saying the following:

```

/Users/luismartins/Sites/temp/disclosure/lib/kirki/includes/class-kirki-fonts-script.php:31
```

Call Stack:

```
Kirki_Fonts_Script->google_link()
Kirki_Fonts_Script->google_font()
do_action('wp_enqueue_scripts')
wp_enqueue_scripts()
do_action('wp_head')
wp_head()
TimberTwig->exec_function()
__TwigTemplate_50afa2f6e8e76ba3c5f1c8b5a645494d55f326e8475bb8ba04c396a1680507cf->doDisplay()
Twig_Template->displayWithErrorHandling()
Twig_Template->display()
__TwigTemplate_0e599b14a3ea0fb23587e90ef20b05ef85d49dec4922ccfa8494750778a95a00->block_html_head_container()
Twig_Template->displayBlock()
__TwigTemplate_0e599b14a3ea0fb23587e90ef20b05ef85d49dec4922ccfa8494750778a95a00->doDisplay()
Twig_Template->displayWithErrorHandling()
Twig_Template->display()
__TwigTemplate_3dc7d5a5d1552335ba12d7d91632552001d74716f4272f0f76482d3e9961180f->doDisplay()
Twig_Template->displayWithErrorHandling()
Twig_Template->display()
Twig_Template->render()
Twig_Environment->render()
TimberLoader->render()
Timber::compile()
Timber::render()
```

I've looked at the code but cant find the issue, the line "affected" is:

```
$value = get_theme_mod( $control['setting'], $control['default'] );
```

Any tips?

**Comment by aristath** [comment]
Currently lines 28-31 in the `class-kirki-fonts-script.php` look like this:

``` php
        foreach ( $controls as $control ) {

            // The value of this control
            $value = get_theme_mod( $control['setting'], $control['default'] );

```

Try replacing those with this and let me know if that fixes the issue:

``` php
        foreach ( $controls as $control ) {

            $control = Kirki_Controls::control_clean( $control );

            // The value of this control
            $value = get_theme_mod( $control['settings'], $control['default'] );

```

**Comment by aristath** [comment]
Actually just try pulling the latest commit and test if that works.... 
I think I fixed it on https://github.com/aristath/kirki/commit/70b5890

**Comment by lmartins** [comment]
I've pulled the latest commit but sadly it still shows the notice, a lot of them ;)

Full trace:

```
[15-Mar-2015 13:28:16 UTC] PHP Notice:  Undefined index: default in /Users/luismartins/Sites/temp/disclosure/lib/kirki/includes/class-kirki-fonts-script.php on line 33
[15-Mar-2015 13:28:16 UTC] PHP Stack trace:
[15-Mar-2015 13:28:16 UTC] PHP   1. {main}() /Users/luismartins/Sites/index.php:0
[15-Mar-2015 13:28:16 UTC] PHP   2. require() /Users/luismartins/Sites/index.php:17
[15-Mar-2015 13:28:16 UTC] PHP   3. require_once() /Users/luismartins/Sites/wp-blog-header.php:16
[15-Mar-2015 13:28:16 UTC] PHP   4. include() /Users/luismartins/Sites/wp-includes/template-loader.php:74
[15-Mar-2015 13:28:16 UTC] PHP   5. Timber::render() /Users/luismartins/Sites/temp/disclosure/front-page.php:65
[15-Mar-2015 13:28:16 UTC] PHP   6. Timber::compile() /Users/luismartins/Sites/wp-content/plugins/timber-library/timber.php:321
[15-Mar-2015 13:28:16 UTC] PHP   7. TimberLoader->render() /Users/luismartins/Sites/wp-content/plugins/timber-library/timber.php:287
[15-Mar-2015 13:28:16 UTC] PHP   8. Twig_Environment->render() /Users/luismartins/Sites/wp-content/plugins/timber-library/lib/timber-loader.php:69
[15-Mar-2015 13:28:16 UTC] PHP   9. Twig_Template->render() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php:293
[15-Mar-2015 13:28:16 UTC] PHP  10. Twig_Template->display() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:274
[15-Mar-2015 13:28:16 UTC] PHP  11. Twig_Template->displayWithErrorHandling() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:263
[15-Mar-2015 13:28:16 UTC] PHP  12. __TwigTemplate_3dc7d5a5d1552335ba12d7d91632552001d74716f4272f0f76482d3e9961180f->doDisplay() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:289
[15-Mar-2015 13:28:16 UTC] PHP  13. Twig_Template->display() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code:33
[15-Mar-2015 13:28:16 UTC] PHP  14. Twig_Template->displayWithErrorHandling() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:263
[15-Mar-2015 13:28:16 UTC] PHP  15. __TwigTemplate_0e599b14a3ea0fb23587e90ef20b05ef85d49dec4922ccfa8494750778a95a00->doDisplay() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:289
[15-Mar-2015 13:28:16 UTC] PHP  16. Twig_Template->displayBlock() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code:29
[15-Mar-2015 13:28:16 UTC] PHP  17. __TwigTemplate_0e599b14a3ea0fb23587e90ef20b05ef85d49dec4922ccfa8494750778a95a00->block_html_head_container() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:154
[15-Mar-2015 13:28:16 UTC] PHP  18. Twig_Template->display() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code:224
[15-Mar-2015 13:28:16 UTC] PHP  19. Twig_Template->displayWithErrorHandling() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:263
[15-Mar-2015 13:28:16 UTC] PHP  20. __TwigTemplate_50afa2f6e8e76ba3c5f1c8b5a645494d55f326e8475bb8ba04c396a1680507cf->doDisplay() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Template.php:289
[15-Mar-2015 13:28:16 UTC] PHP  21. call_user_func_array:{/Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code:70}() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code:70
[15-Mar-2015 13:28:16 UTC] PHP  22. TimberTwig->exec_function() /Users/luismartins/Sites/wp-content/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code:70
[15-Mar-2015 13:28:16 UTC] PHP  23. call_user_func_array:{/Users/luismartins/Sites/wp-content/plugins/timber-library/lib/timber-twig.php:191}() /Users/luismartins/Sites/wp-content/plugins/timber-library/lib/timber-twig.php:191
[15-Mar-2015 13:28:16 UTC] PHP  24. wp_head() /Users/luismartins/Sites/wp-content/plugins/timber-library/lib/timber-twig.php:191
[15-Mar-2015 13:28:16 UTC] PHP  25. do_action() /Users/luismartins/Sites/wp-includes/general-template.php:2197
[15-Mar-2015 13:28:16 UTC] PHP  26. call_user_func_array:{/Users/luismartins/Sites/wp-includes/plugin.php:496}() /Users/luismartins/Sites/wp-includes/plugin.php:496
[15-Mar-2015 13:28:16 UTC] PHP  27. wp_enqueue_scripts() /Users/luismartins/Sites/wp-includes/plugin.php:496
[15-Mar-2015 13:28:16 UTC] PHP  28. do_action() /Users/luismartins/Sites/wp-includes/script-loader.php:923
[15-Mar-2015 13:28:16 UTC] PHP  29. call_user_func_array:{/Users/luismartins/Sites/wp-includes/plugin.php:496}() /Users/luismartins/Sites/wp-includes/plugin.php:496
[15-Mar-2015 13:28:16 UTC] PHP  30. Kirki_Fonts_Script->google_font() /Users/luismartins/Sites/wp-includes/plugin.php:496
[15-Mar-2015 13:28:16 UTC] PHP  31. Kirki_Fonts_Script->google_link() /Users/luismartins/Sites/temp/disclosure/lib/kirki/includes/class-kirki-fonts-script.php:102
```

**Comment by aristath** [comment]
Can you please check again?
I just added an extra check...
If you haven't added a `default` value in your controls, this should fix it.

**Comment by lmartins** [comment]
Looks like we're cleared!  Thanks Aristeides. :+1:

**Comment by aristath** [comment]
:+1: I'm glad we managed to resolve this one!

Thanks for testing it... People like you really help us improve this.

**Comment by lmartins** [comment]
Cool! Well, I'm hoping to a better helper as my skills evolve. Thanks for all the work. :)
