### ISSUE TITLE
Editor field

### ISSUE THREAD

**Issue by thatvideowebguy** [themeum/kirki#968]
### Issue description:

Is there a way to have a working wysiwyg Wp editor field ?
I tried the editor Type, but I'm experciencing some bug 
Info not saved, can't clic on save (not active), link not displayed ...
I didn't found more on this type (editor) on the doc.
Still in developpment ?
Thanks 
### Version used:

 github
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

_s_Kirki::add_field( '_s_theme', array(
    'type'        => 'editor',
    'settings'    => 'footer_txt',
    'label'       => esc_attr__( 'Texte du footer', 'my_textdomain' ),
    'section'     => 'footer',
    'priority'    => 10,

) );
<?php $footer_txt = get_theme_mod( 'footer_txt','');

echo $footer_txt;?>

**Comment by thatvideowebguy** [comment]
Hello again, same issue, 

No way to add color  on the editor ?

Thanks

**Comment by thatvideowebguy** [comment]
Hello again, 
No one facing similar issue with the editor field ? 

now , all seems working excepting adding link and color to text (no button for this one) ? Anyone ?
Thanks

**Comment by nickkuijpers** [comment]
Not working by me ;(

**Comment by thatvideowebguy** [comment]
+1

**Comment by rinkuyadav999** [comment]
https://github.com/aristath/kirki/issues/1046

**Comment by thatvideowebguy** [comment]
we can add some options to the editor field by editing ; includes\field\class-kirki-field-editor.php

```
`		         public static function add_editor() {
			   ( 'tiny_mce' );
```

			echo '<div id="kirki_editor_pane" class="hide">';
			wp_editor( '', 'kirki-editor', array(
				'_content_editor_dfw' => false,
				'drag_drop_upload'    => true,
				'tabfocus_elements'   => 'content-html,save-post',
				'editor_height'       => 200,
				// 'default_editor'      => 'tinymce',
				'teeny'               => false,
				'media_buttons' => false,
				'tinymce'             => array(
					'resize'             => false,
					'wp_autoresize_on'   => false,
					'add_unload_trigger' => false,
				),
			) );
			echo '</div>';
			do_action( 'admin_footer' );
			do_action( 'admin_print_footer_scripts' );
		}`
but there's a lot of bug on css ( add link, dropdown styles and color, ...) 
we have to modify css:;  z-index.

**Comment by rinkuyadav999** [comment]
https://github.com/aristath/kirki/pull/1246

**Comment by aristath** [comment]
This has been fixed in the develop branch, closing.

**Comment by maxviewup** [comment]
I am using the version 3.0.10 and still cannot use some wysiwig features (color, etc).

![screenshot](https://user-images.githubusercontent.com/28163070/31465774-5847ccd2-aeab-11e7-986e-3dc7e3af547a.png)

**Comment by rhcarlosweb** [comment]
Hello, i have a problem with editor settings
How can i enable text color button on editor? @aristath
